api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
spring:
  datasource:
    url: jdbc:sqlite:memory:myDb?cache=shared
    username: sa
    password: sa
    application:
      name: trilhabackend
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      dll-auto: update
      hbm2ddl:
        auto: update